name: CICD-Deployment-with-Elastic-Beanstalk

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Build-Deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Clone repository into server
              uses: actions/checkout@v3
              
            - name: Set up Java & Maven
              uses: actions/setup-java@v2
              with:
                java-version: '11'
                distribution: 'adopt'

            - name: Sonarqube analysis
              run: mvn sonar:sonar -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_LOGIN}}

            - name: Build WAR package
              run: mvn clean package 
            
            - name: Upload package into artifact repository
              run: mvn --batch-mode deploy
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Authenticate into AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{secrets.AWS_REGION}}

            - name: Upload artifact into an s3 bucket
              run: aws s3 cp target/*war s3://xashy-web-app-artifactory

            - name: Create an application version
              run: |
                aws elasticbeanstalk create-application-version \
                --application-name xashy-webapps \
                --source-bundle S3Bucket="xashy-web-app-artifactory",S3Key="xashy-webapp.war" \
                --version-label "ver-${{ github.sha }}" \
                --description "commit-sha-${{ github.sha }}"

            - name: Deploy app to elastic beanstalk environment
              run: aws elasticbeanstalk update-environment --environment-name Xashy-webapps-env --version-label "ver-${{ github.sha }}" --version-label "ver-${{ github.sha }}"

            